name: "Validate"
on:
  workflow_dispatch:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: devcontainers/action@v1
        with:
          validate-only: "true"
          base-path-to-features: "./src"
